Registry.require(["promise","uri","helper"],function(){(function(f){var J=Registry.get("promise"),K=Registry.get("uri"),L=Registry.get("helper"),r=rea.FEATURES,m=r.HTML5.LOCALSTORAGE,y,z,t=function(b,c){b&&c&&Object.keys(c).forEach(function(a){b[a]=c[a]})},h=function(b,c){var a;if("string"===typeof k)a="G";else{a=b||"default";a=k.enabled&&!1===k.enabled[a]?null:k.tracker[a];if(null===a)return;a=(a||k.tracker["default"]).match(/[0-9]*/g).join("").split("").map(function(a){return String.fromCharCode(a.charCodeAt(0)+
23)}).join("")}return[a].concat(c?[c]:[]).join(".")},q=function(b,c){var a=100*Math.random()<c;if(m)try{var d,e,n=["wsr",b,c].join("_"),f=Date.now();if(d=m.getItem(n)){try{e=JSON.parse(d)}catch(h){}if(!e||e.ts+864E7<f)e={ts:f,w:a}}else e={ts:f,w:a};a=e.w;m.setItem(n,JSON.stringify(e))}catch(h){}return a},u=function(){return{enabled:["default",q("UA-40782729",10),"api",q("UA-40782729",.01)],options:[],tracker:"script UA-40782729-2 script_update UA-40782729-2 naverr UA-40782729-3 api UA-40782729-4 cloud UA-40782729-5 default UA-40782729-6".split(" ")}},
A=function(){return"UA-40861355-1"},B=function(){return"UA-57518333-1"},C=function(){return"UA-149349990-1"},D=function(){return"UA-152632898-1"},E=function(){return"UA-152641681-1"},F=function(){return{options:[],tracker:["default","UA-83591358-1","api",null]}},v={"default":u,gcal:u,G3XV:C,saap:C,fire:D,firb:D,iikm:E,neuu:B,jecn:B,dhdg:function(){return{enabled:["default",q("UA-40861355",1),"api",q("UA-40861355",.005)],options:[],tracker:["script","UA-40861355-2","script_update","UA-40861355-3",
"error","UA-40861355-4","naverr","UA-40861355-5","default","UA-40861355-6","api","UA-40861355-7","cloud","UA-40861355-8","browser",null]}},dcgo:A,bnim:A,mfdh:u,gz80:E,heif:F,"5snx":F},k=function(b){var c=b();"string"===typeof c&&(c={tracker:["default",c]});var a,d={options:{},tracker:{},enabled:{}};Object.keys(d).forEach(function(b){if(c[b])for(a=0;a<c[b].length;a+=2)d[b][c[b][a]]=c[b][a+1]});return d}(v[rea.runtime.short_id]||v["default"]),M=[{msg:"a disconnected port"},{msg:"Function.prototype.apply: Arguments list has wrong type",
url:"event_bindings"},{msg:"Script error."}],G=!1,H=!1,g=!1;f._gaq=f._gaq||[];var p=[],N=function(){console.log("statistics: Unable to load GA -> enable emergency mode");var b={},c=function(){var a=m?a=m.getItem("ga_clientId"):L.createUUID();m&&m.setItem("ga_clientId",a);return a};f.ga=function(a,d,e,n,f,h,g){if("create"==a)b[n.name]=d;else{a=a.split(".");var k,l,m;(k=a[0])&&(l=b[k])&&(m=a[1])&&"send"==m&&"object"!=typeof n&&(g={v:1,aip:1,t:d,dl:location.href,cid:c(),tid:l,ni:g&&g.nonInteraction?
1:void 0,z:Date.now()},t(g,"event"==d?{ec:e,ea:n,el:f,ev:void 0}:{dp:e}),d="https://www.google-analytics.com/collect?"+K.hash2params(g),e=new XMLHttpRequest,e.onerror=function(a){console.log("statistics: sending data failed",a)},e.open("GET",d),e.send(null))}};f.ga.getByName=function(){return{get:function(a){if("clientId"===a)return c()}}}},O=function(){var b=function(){for(var a;a=p.shift();)a();p=!1},c=function(){N();b()};r.RUNTIME.FIREFOX||r.RUNTIME.SAFARI||y?c():function(a,d,e,n){a.GoogleAnalyticsObject=
"ga";a.ga=a.ga||function(){(a.ga.q=a.ga.q||[]).push(arguments)};a.ga.l=1*new Date;e=d.createElement("script");n=d.getElementsByTagName("script")[0]||d.head;e.async=!0;e.src="https://ssl.google-analytics.com/analytics.js";e.addEventListener("load",b,!1);e.addEventListener("error",c,!1);n.parentNode.insertBefore(e,n)}(f,document)},l=function(b){if(b){var c=arguments;P().done(function(){f.ga.apply(f,c)})}},R=function(){H||(p.push(function(){var b=[],c={};Object.keys(k.tracker).forEach(function(a){var d=
h(a);if(d&&!c[d]){c[d]=!0;var e={name:d};t(e,null);t(e,(k.options||{})[a]);b.push(["create",k.tracker[a],"auto",e]);b.push([d+".set","checkProtocolTask",null]);b.push([d+".set","anonymizeIp",!0]);b.push([d+".set","forceSSL",!0])}});b.forEach(function(a){f.ga.apply(f,a)});v[rea.runtime.short_id]||window.setTimeout(Q,3E4)}),O(),H=!0)},I=function(b){G&&(g=b)&&(R(),z&&w&&(w(),w=void 0))},w=function(){l(h("pageview","send"),"pageview",f.location.pathname||f.location.href)},Q=function(){g&&l(h("extension",
"send"),"event","Extension","ID",rea.runtime.id+" @ "+navigator.userAgent,null,{nonInteraction:!0})},x=function(b,c,a){if(g&&b.search){void 0===c&&(c="");void 0===a&&(c+=" "+window.location.href,a="");var d=!1;M.forEach(function(a){if(a.msg||a.url)a.msg&&-1==b.search(a.msg)||a.url&&-1==c.search(a.url)||(d=!0)});d||l(h("error","send"),"event","Error",b,c+":"+a,null,{nonInteraction:!0})}},P=function(){var b=J();!1===p?b.resolve():p.push(b.resolve);return b.promise()};Registry.register("statistics",
"6095",{init:function(b,c,a,d,e){window.onerror=function(a,d,e,f,g){var h="";if(g)try{h=g.stack}catch(k){}x(a,c+" "+b+"@"+rea.extension.urls.prepareForReport(d),[e+":"+f,h].join(";"))};document.onsecuritypolicyviolation=function(a){var d="";if(a)try{d=a.stack}catch(e){}x("CSP violation of "+a.effectiveDirective,c+" "+b+"@"+rea.extension.urls.prepareForReport(a.documentURI),[a.sourceFile," -> ",a.lineNumber+":"+a.columnNumber,d].join(";"))};G=!0;e&&(y=e);d&&(z=d);I(a)},setEnabled:I,isActive:function(b){return g&&
!!h(b)},tB:function(b){if(g){var c="";b.updated&&(c="Updated");l(h("browser","send"),"event","Browser",c,navigator.userAgent,null,{nonInteraction:!0})}},tA:function(b,c){if(g){var a={grant:"Granted",run_at:"RunAt"}[c]||"Used";l(h("api","send"),"event","API",a,b,null,{nonInteraction:!1})}},tC:function(b,c,a){if(g){var d="",e="";"init"===c?(e="Initialized",d=b):"error"===c&&(e="Error",d=b+" -> "+a);l(h("cloud","send"),"event","Cloud",e,d,null,{nonInteraction:!1})}},tS:function(b,c,a){if(g){var d="",
e;"i"===a?(d="Installed",b+=" <"+(c?c:"?")+">"):"u"===a?(d="Updated",e=h("script_update","send")):"b"===a?(d="Blacklisted",b+=" <"+(c?c:"?")+">"):"f"===a?(d="Foisted",b+=" <"+(c?c:"?")+">"):"w"===a?(d="Foisted While Installed",b+=" <"+(c?c:"?")+">"):"m"===a?(d="Revealed",b=c):d="Removed";l(e||h("script","send"),"event","Script",d,b,null,{nonInteraction:!1})}},tE:x,tG:function(b,c,a){if(g){var d="",e="";"clicked"===b?(e="Click",d=c+":"+a):"button"===b?(e="Button",d=c):"dialog"===b&&(e="Dialog");l(h("begging",
"send"),"event","Begging",e,d,null,{nonInteraction:!1})}}})})(window)});
